### ISSUE TITLE
Feature request: Card

### ISSUE THREAD

**Issue by timschoch** [SchweizerischeBundesbahnen/sbb-angular#123]
**Is your feature request related to a problem? Please describe.**
We'd like to have teaser elements or grouped content that would fit nicely in a card.

**Describe the solution you'd like**
For us, we'd like to see two designs:
One that looks like a accordion, without the open/c,lose.
![grafik](https://user-images.githubusercontent.com/10527318/62351034-c02a3900-b504-11e9-8df4-8c04c2b7ce40.png)

**Use Cases:** 
- some additional content in the right column that does not need the added cognitive load of the open/close button
- important Filters/Elements that we don't want to the user to be able to hide

And then we have a teaser element, that links to something.
![grafik](https://user-images.githubusercontent.com/10527318/62351256-4d6d8d80-b505-11e9-8d35-dade3f1e74f5.png)

**Use Cases:**
- Product Teasers on the cockpit

**Describe alternatives you've considered**
We're using the accordion for the first one and the second one is still in our backlog

**Comment by kyubisation** [comment]
Could I ask you to open an issue in [sbb-design-systems](https://github.com/sbb-design-systems/sbb-design-system/issues/new/choose)?
We will have a meeting next monday on how UX will handle issues in that repo.
This seems fairly simple to do, but I would like specification/an ok from UX.

**Comment by timschoch** [comment]
Done: https://github.com/sbb-design-systems/sbb-design-system/issues/8
