### ISSUE TITLE
Bug: Radio-Button change-Event IE11 vs Chrome

### ISSUE THREAD

**Issue by efux** [SchweizerischeBundesbahnen/sbb-angular#126]
**Describe the bug**
(change)-Event behaves different in IE11 and Chrome and functionality differs from event on native radio button.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-sbb-uahp3d in Chrome
2. Open Console
3. Click on Radio Button
4. Click on Native-Radio Button
5. Check console, you should see 'SBB A' and 'Native A'
6. Perform steps 1-4 in IE11
7. Output is now undefined and 'Native A'

**Expected behavior**
Both browsers should behave the same way and also the SBB Radio Button should with the (change)-Event behave the same way as the native radio button. 

**Desktop (please complete the following information):**
 - Browser IE11 vs Chrome

**Additional context**
If desired I can make a fix for this, however, I don't know if this is a bug or intended.

**Comment by kyubisation** [comment]
This is definitely a bug.
A PR would be appreciated. 😃

**Comment by uzysset** [comment]
It seems as  IE11 calls the (change) event before updating the [(ngModel)]....

@kyubisation The documentation (https://angular.app.sbb.ch/latest/content/radio-button) regarding sbb-radio-buttons is really weak, how should they be used with reactive forms?

**Comment by kyubisation** [comment]
@uzysset Currently each sbb-radio-button requires `[(ngModel)]` or `formControlName="..."` to be assigned. I'm considering adding a group component/directive and move the model connection to that.

**Comment by kyubisation** [comment]
@uzysset #186 adds a sbb-radio-group element, which can have [(ngModel)] or formControlName assigned to it. The documentation is also updated and extended accordingly.
The form control assignment to the sbb-radio-button and sbb-radio-button-panel is now deprecated.
