### ISSUE TITLE
Slow building workflow

### ISSUE THREAD

**Issue by daniele92vp** [SchweizerischeBundesbahnen/sbb-angular#129]
Takes a lot of time to build the entire project. The workflow slow down and takes a lot of time to just make few changes.

Can be achieved a little improvement by building only specific part of the project, but still slow and need to restart the development server every time.

**Comment by kyubisation** [comment]
Is this from the view of the consumer or developer of sbb-angular? Either way #147 should help with that, but it takes a bit of an effort to refactor.

**Comment by kyubisation** [comment]
As for the development cylce. This cannot be easily changed right now. Maybe with Bazel (ETA Angular 9) this could be addressed.

I will close this issue fow now.

**Comment by daniele92vp** [comment]
Yes I think the #147 will help a lot. Already when developing by modifying the imports, changes are applied immediately.
