### ISSUE TITLE
Bug: Autocomplete lags/freezes when clearing input

### ISSUE THREAD

**Issue by uzysset** [SchweizerischeBundesbahnen/sbb-angular#144]
**Describe the bug**
When clearing the input field of a autocomplete field, the Browser starts to lag or even freezes for a few second.

**To Reproduce**
1. Go to https://angular.app.sbb.ch/latest/content/autocomplete
2. Open the tap 'Examples'
3. Click in the first autocomplete field
4. Enter any random long string ie. 'asjkadkjaskjdjasdjasjdalsdklj'
5. Start clearing the autocomplete field by pressing the backspace button
6. When reaching the last character on the input query, the browser will start lagging and stays unresponsive for a few seconds.

**Expected behavior**
Entering/Clearing the autocomplete field should not have any influence on its performance

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version Version 76.0.3809.100 (Offizieller Build) (64-Bit)

**Additional context**
It seems as the issue is not directly related with the size of the available (autocompleted) options, but rather connected to the usage of the HighlightPipe used in AutocompleteTriggerDirective.highlightOptionsByInput()

**Comment by kyubisation** [comment]
Thank you for the investigation. I'll see if I can fix this.
