### ISSUE TITLE
Bug: DatePicker has incorrect Tab behaviour in IE11

### ISSUE THREAD

**Issue by uzysset** [SchweizerischeBundesbahnen/sbb-angular#155]
**Describe the bug**
When using 'Tab' to iterate through a DatePicker with a Toggle (the calendar icon) in IE11, the tab disappears once before and once right after focusing on the Toggle. Firefox and Chrome work both as intended

**To Reproduce**
1. Go to 'https://angular.app.sbb.ch/latest/content/datepicker'
2. Click on 'Examples'
3. Tap through the datepickers with the toggle activated 
4. Tab is lost in IE11

**Expected behavior**
Correct tab behaviour without 'nirvana tabs' ;)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser IE11
 - Version 11.885.17134.0

**Comment by kyubisation** [comment]
Reason: SVGs are tabbable in IE11.
TODO: Add `focusable="false"` to svg.
