### ISSUE TITLE
Issues with Text Area

### ISSUE THREAD

**Issue by kyubisation** [SchweizerischeBundesbahnen/sbb-angular#16]
Copied from https://issues-ext.sbb.ch/browse/SACL-154

Issues with Text Area
Edge:

- When there is a large paragraph the box is kind of endless to the left (like a normal input field) so there is no new line made.

General:

- When there is a large paragraph inside and I delete the whole text the text area has an unexpected behaviour as the filed isn't resized till i type some letters, each typed letter removes one line of the text are.
- When the input data is empty it automatically shows "undefined" as a placeholder.

**Comment by kyubisation** [comment]
Sizing can be solved via css (e.g. max-width).

**Comment by mghilardelli** [comment]
The issue with Edge is not fixed yet. In Edge the text area doesn't break the line without an "ENTER". 

![Media1](https://user-images.githubusercontent.com/19152082/60270589-06cab900-98f1-11e9-868f-0107ff85fd0c.gif)

**Comment by mghilardelli** [comment]
> The issue with Edge is not fixed yet. In Edge the text area doesn't break the line without an "ENTER".
> ![bug](https://user-images.githubusercontent.com/19152082/60270783-64f79c00-98f1-11e9-9659-3117627fb7f6.gif)

this css rule fixes the issue
` white-space: pre-wrap`
