### ISSUE TITLE
Bug: Autocomplete option list is fixed on vertical window scroll 

### ISSUE THREAD

**Issue by zer0p1** [SchweizerischeBundesbahnen/sbb-angular#161]
**Describe the bug**
The autocomplete option list postion apears to be fixed when scrolling vertical in browsers window.

**To Reproduce**
1. Go to [Autocomplete](https://sbb-angular.app.sbb.ch/latest/public/components/autocomplete)
2. Shrink browser window until vertical scrollbar appears
3. Scroll up and down in browser window

**Expected behavior**
The autocomplete option list should not be fixed while scrolling.

**Screenshots**

![bug_autcomplete_option_list](https://user-images.githubusercontent.com/50302840/64622728-146be700-d3e8-11e9-80dd-2dcc959a5126.gif)

**Comment by kyubisation** [comment]
The reason is the usage of the perfect scrollbar, since the CDK portal loses track of the connected element.
Needs to be investigated, whether a custom ScrollStrategy would solve this.
