### ISSUE TITLE
Problem with sbb-field

### ISSUE THREAD

**Issue by kyubisation** [SchweizerischeBundesbahnen/sbb-angular#18]
Copied from https://issues-ext.sbb.ch/browse/SACL-149

When sbb-fields are used with a FormGroup there is the following console error from sbb-angular. But everything is working as expected.

**Comment by kyubisation** [comment]
Example found in https://code.sbb.ch/projects/KD_PSDR/repos/psdr-frontend/browse/src/app/modules/contract/components/contract-form/contract-form.component.html

**Comment by kyubisation** [comment]
Unable to reproduce
Please provide a reproduction with StackBlitz: https://stackblitz.com/fork/angular-axrgm3

**Comment by mghilardelli** [comment]
> Unable to reproduce
> Please provide a reproduction with StackBlitz: https://stackblitz.com/fork/angular-axrgm3

Seems to be fixed in the latest version.
