### ISSUE TITLE
Bug: sbb-toggle change from outside not reflected when changing form

### ISSUE THREAD

**Issue by jeripeierSBB** [SchweizerischeBundesbahnen/sbb-angular#184]
**Describe the bug**
When using ReactiveFormsModule and the whole form is changed, changes are not reflected in sbb-toggle.

**To Reproduce**
1. Go to https://stackblitz.com/edit/angular-sbb-wcslva
2. Wait 1 second
3. "false" should be selected
4. "false" is not selected

**Expected behavior**
sbb-toggle should always display state of connected form

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by kyubisation** [comment]
This should be partially resolved by #186.
However, I don't think it's a good idea to create a new FormControl. The FormControl should be changed/updated via form.setValue(newValue).

**Comment by jeripeierSBB** [comment]
Thank you for fixing it :) We also thought about changing the strategy to replace the form, but with patchValue or setValue i did not work as well.
