### ISSUE TITLE
Lightbox closes on datepicker arrow click

### ISSUE THREAD

**Issue by kyubisation** [SchweizerischeBundesbahnen/sbb-angular#19]
Copied from https://issues-ext.sbb.ch/browse/SACL-148

I have a Lightbox with a form inside and there is a datepicker with 2 date for a range with master-slave. I have the arrows activated. When I click on an arrow the Lightbox unexpectedly closes. The date is updated. In the Lightbox there is a function called abort to close the abort (thats presumably the issue)

**Comment by kyubisation** [comment]
Unable to reproduce
Could you provide a reproduction via https://stackblitz.com/fork/angular-axrgm3

**Comment by mghilardelli** [comment]
> Unable to reproduce
> Could you provide a reproduction via https://stackblitz.com/fork/angular-axrgm3

Couldn't reproduce the bug as well. In my view you can close this issue.
