### ISSUE TITLE
Feature request: SBB Styled Card

### ISSUE THREAD

**Issue by mischahaenen** [SchweizerischeBundesbahnen/sbb-angular#206]
**Is your feature request related to a problem? Please describe.**
Ich habe schon des öfteren Cards erstellt. Diese habe ich entweder mit Material oder Bootstrap erstellt und sie umgestyled, so dass sie einen SBB look bekommen. Ist es möglich ein neues CardModule zu entwickeln?

**Describe the solution I'd like**
See solution on https://www.sbb.ch/de/ under "Rund um die SBB"

**Comment by kyubisation** [comment]
For this you need to open a Website Feature Request in [sbb-design-systems/sbb-design-system](https://github.com/sbb-design-systems/sbb-design-system/issues/new/choose)
