### ISSUE TITLE
Feature request: add title to notifications

### ISSUE THREAD

**Issue by timschoch** [SchweizerischeBundesbahnen/sbb-angular#212]
**Is your feature request related to a problem? Please describe.**
We have larger notification messages where we need a title to give the user some context at what they are looking without reading the whole message.
![grafik](https://user-images.githubusercontent.com/10527318/68131061-b279ba80-ff1c-11e9-84f6-35e2476cd9ec.png)

**Describe the solution you'd like**
Besides the message field we'd like to see a title that can be optionally filled. It gets displayed as bold text on a new line.

**Describe alternatives you've considered**
If formatting in the text would be allowed, that could be mimicked. But we prefer a structured approach to make sure it gets used properly throughout the application.

**Additional context**
I had a chat with @frenggi today and he agreed this would make sense. If this is fine for you @kyubisation, we'd provide a PR for this feature.

**Comment by kyubisation** [comment]
We do not currently offer an implementation of notifications for the business variant: #83 
We would need a PR for that first.
I do agree, that this would be nice to have.

**Comment by timschoch** [comment]
Oh nevermind, I didn't remember that Feature request. Closed.
