### ISSUE TITLE
Feature request: Processflow should have a non forced flow mode

### ISSUE THREAD

**Issue by zer0p1** [SchweizerischeBundesbahnen/sbb-angular#213]
**Is your feature request related to a problem? Please describe.**
Currently it's only possible to navigate to a spefific step by clicking on a step which the user has already passed. There are use cases where we won't force the user to meet a spefific flow. 

**Describe the solution you'd like**
It should be possible to click on any next or previous step in Processflow header to get to a specfifc step. There should be an additional input property (e.g. forceFlow = false) which disables a given specific flow.

![grafik](https://user-images.githubusercontent.com/50302840/68137451-4e102880-ff27-11e9-8776-f581e40fe754.png)

**Comment by kyubisation** [comment]
This is already possible with the `skippable` property: https://angular.app.sbb.ch/latest/business/components/processflow (See `Skippable step configuration`)

**Comment by zer0p1** [comment]
Thank's for the quick response :smiley: Didn't noticed that processFlow component of angular-public and angular-business have different features..

**Comment by kyubisation** [comment]
No problem. Some business components have additional functionality in comparison with their public counterparts.
