### ISSUE TITLE
Datepicker slave opens when master value changes

### ISSUE THREAD

**Issue by daniel-sc** [SchweizerischeBundesbahnen/sbb-angular#36]
When using Datepicker in master/slave setup one currently cannot set the value of the master without having the slave opening the popup. This is a problem when setting the value programmatically.

**Comment by kyubisation** [comment]
Looking at `4.3 Datumsbereich` of https://digital.sbb.ch/de/websites/components/datepicker the datepicker currently triggers under incorrect conditions. It should only trigger when the master date is selected via calendar or when a newer master date than the slave date is selected.
