### ISSUE TITLE
TableComponent pinmode doesn't work properly with IE

### ISSUE THREAD

**Issue by zer0p1** [SchweizerischeBundesbahnen/sbb-angular#58]
TableComponent pinmode 'on' doesn't work as expected in IE. This should be fixed or documented if no fix for IE aviable.

**Comment by kyubisation** [comment]
Yes, it requires support for position: sticky, which is not available in IE.
This should have been documented, but currently isn't.
We will add documentation for that.

**Comment by timschoch** [comment]
Could you provide a Fallback for IE that sets the table (or the Container) to `overflow-x: auto;`?
This way we have a gracefull degradation and the table is still usable.

We have data heavy tables (Reports) that require more space than available and a lot of our customers still use IE11. Doing nothing isn't an option for us.

**Comment by kyubisation** [comment]
@timschoch This should already be the case for sbb-table. Inside sbb-table the table is wrapped by a div with overflow: auto.

**Comment by zer0p1** [comment]
Nevertheless the pinmode still seems to be incompatible with IE:

- In our case the scroll bar is missing exclusively in IE and Edge:
![IE_pinmode_scrollbar](https://user-images.githubusercontent.com/50302840/60503683-7a3d4380-9cc0-11e9-94f1-4f78d8100e11.PNG)

- For SACL democase the pinmode shadow occurs for entire box at its right side exclusively in IE:
![IE_pinmode_shadow](https://user-images.githubusercontent.com/50302840/60504004-10716980-9cc1-11e9-8625-e45ec01b09ca.PNG)

**Comment by kyubisation** [comment]
I can reproduce the shadow being at the wrong place, but I can not reproduce the missing scroll bar.
Could you provide a small reproduction?
