### ISSUE TITLE
Datepicker increments on ENTER

### ISSUE THREAD

**Issue by mghilardelli** [SchweizerischeBundesbahnen/sbb-angular#61]
If Enter is pressed within an input field which is in the same formgroup with a master-slave datepicker, the first datepicker increments its date.

**Comment by kyubisation** [comment]
Can you provide a reproduction? https://stackblitz.com/fork/angular-sbb

**Comment by mghilardelli** [comment]
You can just try it on https://angular.app.sbb.ch/latest/content/datepicker in the "2 Datepicker" example when you choose a date range, click into the second picker and press ENTER

**Comment by kyubisation** [comment]
The problem is that on enter the first button in a form, which is not configured with type="button" is triggered.
We will fix this inside the datepicker.
