### ISSUE TITLE
feat(business): tabs styling

### ISSUE THREAD

**Issue by kyubisation** [SchweizerischeBundesbahnen/sbb-angular#87]
Design Spec: https://digital.sbb.ch/en/webapps/components/tab

DoD:
- Apply business styling with `$sbbBusiness`, `businessOnly()` and `publicOnly()`. (See autocomplete for reference.)
- Use business tabs in business documentation section

**Comment by uzysset** [comment]
Currently working on this, @kyubisation can you assign me?
